"""Add detailed match scoring fields to Submission model

Revision ID: 49e5ee989490
Revises: 4dbc3827aac6
Create Date: 2025-05-24 23:44:23.891612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49e5ee989490'
down_revision = '4dbc3827aac6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submission', schema=None) as batch_op:
        batch_op.add_column(sa.Column('your_points', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('system_points', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('base_score', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('won_match', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('close_match', sa.Boolean(), nullable=False))
        batch_op.alter_column('score',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submission', schema=None) as batch_op:
        batch_op.alter_column('score',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.drop_column('close_match')
        batch_op.drop_column('won_match')
        batch_op.drop_column('base_score')
        batch_op.drop_column('system_points')
        batch_op.drop_column('your_points')

    # ### end Alembic commands ###
